server:
  port: 8084
spring:
  application:
    name: goods-web
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.0.103
    virtual-host: /sc
    username: rabbitmq
    password: rabbitmq
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:12010/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

