server:
  port: 8089

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql:///db_shoppingcity?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 1000
      test-on-borrow: true
  rabbitmq:
    host: 192.168.56.101
    username: rabbitmq
    password: rabbitmq
    virtual-host: /sc
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 300000ms
        multiplier: 2
      exchange: sc.item.exchange
    publisher-confirm-type: correlated
  redis:
    host: 192.168.0.103
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:12010/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10

mybatis:
  type-aliases-package: cn.dbdj1201.sc.order.pojo
  mapper-locations: mapper/OrderMapper.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  not-empty: false
  identity: mysql
sc:
  worker:
    workerId: 1
    datacenterId: 1
  jwt:
    pubKeyPath: D:\\test\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: SC_TOKEN # cookie的名称
  pay:
    appId: wx8397f8696b538317
    mchId: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    connectTimeoutMs: 5000
    readTimeoutMs: 10000
