server:
  port: 12011
spring:
  application:
    name: sc-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:12010/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service:  /item/** # 商品微服务的映射路径
    search-service: /search/** # 搜索微服务的映射路径
    user-service: /user/** # 用户微服务的映射路径，登录注册
