server:
  port: 12011
spring:
  application:
    name: sc-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:12010/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service:  /item/** # 商品微服务的映射路径
    search-service: /search/** # 搜索微服务的映射路径
    user-service: /user/** # 用户微服务的映射路径，登录注册
    auth-service: /auth/** # 授权中心微服务
    cart-service: /cart/** # 购物车微服务
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
  add-host-header: true #携带请求本身的head头信息
  sensitive-headers: null
sc:
  jwt:
    pubKeyPath: D:\\test\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: SC_TOKEN # cookie的名称
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item