server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.0.103
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:12010/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
sc:
  jwt:
    pubKeyPath: D:\\test\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: SC_TOKEN # cookie的名称